### ISSUE TITLE
[docs] Add missing import to "Installing and initializing the framework" guide

### ISSUE THREAD

**Issue by munichpavel** [microsoft/data-factory-testing-framework#108]
At commit [71c2a25042fbc1e87022657da8e14349b1ca93af of docs/basic/installing_and_initializing_framework.md](https://github.com/microsoft/data-factory-testing-framework/blob/71c2a25042fbc1e87022657da8e14349b1ca93af/docs/basic/installing_and_initializing_framework.md), the first code snippet is missing `TestFrameworkType` in the import statement:

Is 
```python
rom data_factory_testing_framework import TestFramework
test_framework = TestFramework(
        framework_type=TestFrameworkType.DataFactory,
        root_folder_path='/factory',
    )
```

Should be
```python
from data_factory_testing_framework import TestFramework, TestFrameworkType

test_framework = TestFramework(
        framework_type=TestFrameworkType.DataFactory,
        root_folder_path='/factory',
    )
```

**Comment by arjendev** [comment]
Hi @munichpavel,

Thanks for spotting and fixing this!
