### ISSUE TITLE
Expression evaluation of uninitialized String variable

### ISSUE THREAD

**Issue by rn-zeiss** [microsoft/data-factory-testing-framework#120]
I have some pipeline String variables defined that don't have a defaultValue. When really executing the pipeline in Data Factory expressions using such uninitialized variables are I guess evaluated to empty string. Using data-factory-testing-framework the variables are set to 'None' and the evaluation of such expressions is failing with DataFactoryElementEvaluationError, see sample expression below.

Would it be possible to have same behavior in data-factory-testing-framework as in Data Factory?

```
"variables": {
            "temp_str": {
                "type": "String"
            }
        },        

@concat(variables('temp_str'),', [',item(),']',if(contains(item(),' '),concat(' as [',replace(replace(replace(item(),' ','_'),'(',''),')',''),']'),' '))
```

**Comment by arjendev** [comment]
Thanks for another bug-report @rn-zeiss, I will look into this later this week. If you can share a unit test (i.e. with arrange, act and assert portion) which fails with above expression, that would be of great help!

**Comment by arjendev** [comment]
Next Monday, we will be merging the improved expression language runtime based on the original dotnet runtime instead of our python implementation (#118) which will most likely solve your issues and bring the Testing Framework closer to the real Data Factory implementation.

**Comment by arjendev** [comment]
@rn-zeiss, we have deployed the updated runtime. Please have a look at version 1.0.0 and let us know whether that resolves your issues, thanks!

**Comment by rn-zeiss** [comment]
@arjendev, tried with version 1.0.1 and it works. Expressions referencing uninitialized string variables are evaluated as in real pipeline. Thanks :-) this issue can be closed.

**Comment by arjendev** [comment]
Awesome, thanks for letting us know, closing this issue then!
