### ISSUE TITLE
Add guidance on how to approach the framework for a new pipeline

### ISSUE THREAD

**Issue by ydaponte** [microsoft/data-factory-testing-framework#36]
**Goal:** improve the guidance, by adding a step-by-step on the things that need to be considered when starting to test a new pipeline.

**Success criteria:**
- Add guidance (might include visuals) on how to approach the framework for new pipelines (that are not in the examples)
- Add more examples to include often used tasks like the Copy activity for example

**Comment by ydaponte** [comment]
@sreedhar-guda - one of the aspects of this item was the order of the activities in the pipelines vs the order in which the tests were written. Can you clarify if you find the answer to that on our next meeting or offline in the chat?

**Comment by arjendev** [comment]
Fixed in #72
