### ISSUE TITLE
[Question] Support for Synapse Pipelines

### ISSUE THREAD

**Issue by keen85** [microsoft/data-factory-testing-framework#82]
Hi, [project descriptions](https://github.com/microsoft/data-factory-testing-framework?tab=readme-ov-file#data-factory---testing-framework) says:

> A stand-alone test framework that allows to write unit tests for Data Factory pipelines on [Microsoft Fabric](https://learn.microsoft.com/en-us/fabric/data-factory/) and [Azure Data Factory](https://learn.microsoft.com/en-us/azure/data-factory/concepts-pipelines-activities?tabs=data-factory).

Are you thinking about adding support for **Synapse Pipelines** as well?

**Comment by jayachithra** [comment]
Hey @keen85,

Support for Synapse is available in the latest release (1.1.0) of the framework. Would love to hear any feedback and we're here to support if you face any issues. :)
